### ISSUE TITLE
missing requirement db_types

### ISSUE THREAD

**Issue by dtomlinson91** [googleapis/python-bigquery#1188]
Possibly related to #1186

Version 3 added an import `db_types` to [`main/google/cloud/bigquery/table.py`](https://github.com/googleapis/python-bigquery/blob/main/google/cloud/bigquery/table.py#L31-L32).

This is missing as a dependency in `setup.py`.

Workaround is to specify `db_types` as a dependency.

```
Error
2022-03-30T15:02:22.013284720Z from google.cloud import bigquery
Error
2022-03-30T15:02:22.013288448Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
Error
2022-03-30T15:02:22.013292638Z from google.cloud.bigquery.client import Client
Error
2022-03-30T15:02:22.013296358Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 64, in <module>
Error
2022-03-30T15:02:22.013300785Z from google.cloud.bigquery import _job_helpers
Error
2022-03-30T15:02:22.013304550Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/_job_helpers.py", line 24, in <module>
Error
2022-03-30T15:02:22.013308792Z from google.cloud.bigquery import job
Error
2022-03-30T15:02:22.013312588Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/__init__.py", line 27, in <module>
Error
2022-03-30T15:02:22.013316823Z from google.cloud.bigquery.job.copy_ import CopyJob
Error
2022-03-30T15:02:22.013320716Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/job/copy_.py", line 21, in <module>
Error
2022-03-30T15:02:22.013324659Z from google.cloud.bigquery.table import TableReference
Error
2022-03-30T15:02:22.013328347Z File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/table.py", line 32, in <module>
Error
2022-03-30T15:02:22.013350444Z import db_dtypes # type: ignore # noqa
Error
2022-03-30T15:02:22.013354379ZModuleNotFoundError: No module named 'db_dtypes'
```

**Comment by tswast** [comment]
Thanks for the report! Definitely something we should fix ASAP.

**Comment by tswast** [comment]
Since pandas and db-dtypes is an extra, we didn't add it to the requirements, but I did improve the error message when pandas is installed by the db-dtypes package is missing.

**Comment by mattwelke** [comment]
No problem to report here. Just saying thanks for that error message. It's helping people out. :p

```Traceback (most recent call last):
...
    raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception
ValueError: Please install the 'db-dtypes' package to use this function.
```
