### ISSUE TITLE
Field has changed type from DATE to STRING even it is null

### ISSUE THREAD

**Issue by kevindaffaarr** [googleapis/python-bigquery#1340]
Hello everyone, I want to upload a csv from dataframe to my bigquery dataset. Why I'm not use SQLALCHEMY or pandas.to_bgq is because the Query Parameter that their produce is more than 10,000 because I have 818 rows with 29 columns. But I got this error that frustate me after I try and search the google, StackOverflow, and the issue tab.

#### Steps to reproduce
  1. ```data``` as DataFrame that has ```delistingdate``` column
  2. Convert ```data``` to csv
  3. set job_config
  4. run load_table_from_file

#### Code example
With NULL_MARKER
```python
data_csv = data.to_csv(index=False,header=True,na_rep="null")
job_config = bigquery.LoadJobConfig(
	source_format = bigquery.SourceFormat.CSV, skip_leading_rows = 1, autodetect=True,
	write_disposition = bigquery.WriteDisposition.WRITE_APPEND, null_marker="null"
)

job = bq_client.load_table_from_file(
	file_obj = io.StringIO(data_csv),
	destination = f"{BIGQUERY_DATASET_ID}.{tablename}",
	job_config = job_config
)

return job.result()
```

WITHOUT NULL MARKER
```python
data_csv = data.to_csv(index=False,header=True)
job_config = bigquery.LoadJobConfig(
	source_format = bigquery.SourceFormat.CSV, skip_leading_rows = 1, autodetect=True,
	write_disposition = bigquery.WriteDisposition.WRITE_APPEND
)

job = bq_client.load_table_from_file(
	file_obj = io.StringIO(data_csv),
	destination = f"{BIGQUERY_DATASET_ID}.{tablename}",
	job_config = job_config
)

return job.result()
```
#### Stack trace
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "\env\lib\site-packages\google\cloud\bigquery\job\base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "\env\lib\site-packages\google\api_core\future\polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table project:table.stockdata. Field delistingdate has changed type from DATE to STRING
```

Thanks!

**Comment by cholojuanito** [comment]
How exactly did you solve this issue?

**Comment by alkanschtein** [comment]
```
def load_to_bq(uri,table_id,schema_detect_auto=True):
    if schema_detect_auto:
        job_config = bigquery.LoadJobConfig(
            autodetect=True,
            schema_update_options=['ALLOW_FIELD_ADDITION'],
            skip_leading_rows=1,
            source_format=bigquery.SourceFormat.CSV
        )
    else:
        job_config = bigquery.LoadJobConfig(
            schema_update_options=['ALLOW_FIELD_ADDITION'],
            skip_leading_rows=1,
            source_format=bigquery.SourceFormat.CSV
        )     
        
    load_job = BQ.load_table_from_uri(
        uri, table_id, job_config=job_config
    )

    return load_job.result().state
```
I tried this way if it helps

**Comment by Gogoro** [comment]
Had the same issue.
What ended up fixing it for me was to use autodetect=True, and NOT providing a schema when I do appends.

Just leaving it here in case someone else has the same issue.
