### ISSUE TITLE
HTTPSConnectionPool Error: Max retries exceeded...

### ISSUE THREAD

**Issue by lee-uidam** [googleapis/python-bigquery#1359]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Running on Mac M1, Inside Docker Image:  5.10.124-linuxkit SMP PREEMPT  aarch64 GNU/Linux
  - Python version: Python 3.9.13
  - pip version: 22.2.2
  - `google-cloud-bigquery` : Version: 2.3.1

#### Steps to reproduce

I'm using bigquery in a remote jupyter, and below is how I work.
- Using M1 Pro
- Using VPN when accessing admin sites e.g., redash.. (so VPN is sometimes on, sometimes off - And the code works fine on both)
- Running Jupyter Notebook Inside Docker. And using local VSCode to access remote Jupyter in Docker.

Trouble I'm facing
- After initial launch, everything is okay.
- About 30 ~ few hours later while using Bigquery Client, suddenly a query won't execute.
- Thought it could be VS Code's connection problem, so tried the same code inside Docker container, but the same happened.

And after about 5-10 mins, it goes okay again. Everything works fine. 
But it's happening every 1-2 hour, so it's kind of annoying.

Looking forward to your help :) Thanks.

#### Code example

```python
from google.cloud import bigquery
import os

def get_bigquery_client(path={path_to_json_key}):
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = path
    
    client = bigquery.Client()

    return client

bqc = get_bigquery_client()
bqc.query("SELECT 1").to_dataframe() #doesn't work
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff64f8e160>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bigquery.googleapis.com', port=443): Max retries exceeded with url: /bigquery/v2/projects/{project}/jobs?prettyPrint=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff64f8e160>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2809, in query
    query_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1095, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 430, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 636, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 473, in api_request
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 337, in _make_request
    return self._do_request(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 375, in _do_request
    return self.http.request(
  File "/usr/local/lib/python3.9/site-packages/google/auth/transport/requests.py", line 480, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bigquery.googleapis.com', port=443): Max retries exceeded with url: /bigquery/v2/projects/{project}/jobs?prettyPrint=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff64f8e160>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by lee-uidam** [comment]
I found a solution to this.

Whenever something suddenly doesn't work, I tried turning off the VPN and turn it on again, then the problem is gone.

I think it was a VPN related issue.. So I'm closing the issue.

**Comment by stantonius** [comment]
@lee-uidam I'd just like to say thank you for following up that this was a vpn issue for you. This insight solved a problem that I had been struggling with for longer than I'd care to admit (months) and had me seriously questioning my sanity. 

I am using Tailscale VPN on an M1 Mac to tunnel into my GCP VPC network so that a Docker container can communicate with some private APIs. While it is still annoying to have to disable the vpn every so often (and it doesn't solve the issue immediately), it does prevent those weird connection stacktrace errors that I was experiencing, could never replicate, and had me worried for the state of my production code.

So thanks again for taking the time to report back. It saved me many hours.
