### ISSUE TITLE
Client.insert_row raises NotFound on project intermittently

### ISSUE THREAD

**Issue by philippefutureboy** [googleapis/python-bigquery#1396]
#### Description

Given the following simplified code:

```py
table = {...}
table_id = f"{PROJECT}.{dataset(client_id, type='extract')}.{table['identifier']}"
schema = table['schema']
records = _fetch_data(pg_client, client_id, table)

LOG.info("Inserting %s records into table %s", len(records), dest_table_id)
client = bigquery.Client()
client.insert_rows(
    table=dest_table_id,
    rows=records,
    selected_fields=[bigquery.SchemaField.from_api_repr(field) for field in schema],
)
```

Two subsequent, 2-minutes separated runs of the same code & configuration result in two different results.
Configuration is guaranteed to be the same (except the time of run) given that it is an airflow task that is re-run after the first failure, with no side effects except the records (which are stable).

The two different results:

(FAILURE)

```
[2022-11-02, 14:54:40 UTC] {domain.py:36} INFO - Inserting 8 records into table pinkdolphin-prod-4541.prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist
[2022-11-02, 14:54:40 UTC] {domain.py:39} ERROR - 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/pinkdolphin-prod-4541/datasets/prod_cli9464498d16ae45f68438d710677_raw/tables/orca_raw__domain_dentitek_specialist/insertAll?prettyPrint=false: Table 432865716849:prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist not found.
```

(SUCCESS)

```
[2022-11-02, 14:55:45 UTC] {domain.py:36} INFO - Inserting 8 records into table pinkdolphin-prod-4541.prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist
[2022-11-02, 14:55:45 UTC] {python.py:175} INFO - Done. Returned value was: None
```

Notice that on the FAILURE case, the printed project ID is different from the one provided to the client?

```
 Inserting 8 records into table ****pinkdolphin-prod-4541****.prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist
404 POST ...: Table ****432865716849****:prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist not found.
```

Luckily we have airflow to retry the task. No idea what's causing this. I'd venture to say it's a hiccup from the backend, but I think it's important the team knows of this issue so that it can be found and addressed

#### Environment details

  - OS type and version: apache/airflow:2.4.2-python3.8
  - Python version: `3.8.7`
  - pip version: `22.2.2`
  - `google-cloud-bigquery` version: `{version = "2.34.4", extras = ["bqstorage", "pandas"]}`

#### Stack trace
```
[2022-11-02, 14:54:40 UTC] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/dags/dagfiles/clinic_extract_orca/airflow.py", line 12, in extract_orca_table_to_bq_callable
    extract_orca_table_to_bq(src_client, dest_client, clinic_id, table)
  File "/home/airflow/.local/lib/python3.8/site-packages/dags/dagfiles/clinic_extract_orca/domain.py", line 37, in extract_orca_table_to_bq
    dest_client.insert_records(table_id=dest_table_id, schema=schema, records=records)
  File "/home/airflow/.local/lib/python3.8/site-packages/dags/utils/database/_bigquery.py", line 246, in insert_records
    errors = self.client.insert_rows(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3466, in insert_rows
    return self.insert_rows_json(table, json_rows, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 3646, in insert_rows_json
    response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http.py", line 483, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/pinkdolphin-prod-4541/datasets/prod_cli9464498d16ae45f68438d710677_raw/tables/orca_raw__domain_dentitek_specialist/insertAll?prettyPrint=false: Table 432865716849:prod_cli9464498d16ae45f68438d710677_raw.orca_raw__domain_dentitek_specialist not found.

```

Thanks!

**Comment by philippefutureboy** [comment]
I spoke too soon - it did reduce the number of failures, but I started having other types of failures - 404 NotFound: Table is truncated.
So after some research I found out that [these operations are _eventually consistent_](https://stackoverflow.com/questions/70013949/bigquery-404-table-is-truncated-when-insert-right-after-truncate) and that the method of dealing with this is to pass an exponential backoff retry.

**Comment by philippefutureboy** [comment]
Circling back - We have opted to entirely remove calls to `insert_rows` and instead we use Client.query with a parametrized INSERT statement. While way less performant, at least it is 100% reliable.

**Comment by alvarowolfx** [comment]
hey @philippefutureboy , the behavior that you're seeing is a eventual consistency problem, where you're trying to send data to a table that was deleted/re-created. Seems like you already found that per comment https://github.com/googleapis/python-bigquery/issues/1396#issuecomment-1302472023

@carloslme workaround is a good option in a test environment, we do this on a lot of our integration tests. If you need to use the same table and clean data on it, using `TRUNCATE TABLE tableId` can be an option too instead of deleting the table. 

The custom retryer might work, but we don't recommend that, as it can lead to undefined behavior, where we don't know to which version of the table the data is being saved

**Comment by philippefutureboy** [comment]
Hey @alvarowolfx! Thanks for your answer.
In our case since we use this as part of our ELT process and that schema may change over time, we've opted for the solution below:

```py
ddl_query = "CREATE OR REPLACE TABLE ..."
job = client.query(ddl_query)
job.result()
# some more code
job = client.load_table_from_file(
            file,
            table_ref,
            job_config=bigquery.LoadJobConfig(
                source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
                write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            ),
        )
```

Since this solution works with 100% reliability, I'll close this issue. Thanks for your help!
