### ISSUE TITLE
%%bigquery ipython / jupyter notebook magics prerelease tests failing

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery#1530]
Currently getting failing prerelease tests on `main` branch: https://github.com/googleapis/python-bigquery/commit/a2520cabf7ec6bcb923c21e338188f1c10dc4d5d, https://source.cloud.google.com/results/invocations/c18d2f75-e792-4c1e-b0fb-fd4ea7632970/targets, https://source.cloud.google.com/results/invocations/a6ab5f6d-4c9a-401b-9a07-ab55e301e84f/targets

Potential incompatibility between tqdm, ipython, and jupyter widgets packages?

```
tests/unit/test_magics.py .F.Exception ignored in: <function tqdm.__del__ at 0x7eff697bd3a0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
F...............................FException ignored in: <function tqdm.__del__ at 0x7eff697bd3a0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
FException ignored in: <function tqdm.__del__ at 0x7eff697bd3a0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
FException ignored in: <function tqdm.__del__ at 0x7eff697bd3a0>
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/tmpfs/src/github/python-bigquery/.nox/prerelease_deps-3-8/lib/python3.8/site-packages/tqdm/notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
F....... [ 48%]
```

```
self = <ipywidgets.widgets.trait_types.InstanceDict object at 0x7eff68b55c10>
obj = <[ModuleNotFoundError("No module named 'ipykernel'") raised in repr()] FloatProgress object at 0x7eff66707af0>
cls = <class 'ipywidgets.widgets.widget_float.FloatProgress'>

    def get(self, obj, cls=None):
        try:
>           value = obj._trait_values[self.name]
E           KeyError: 'layout'

.nox/prerelease_deps-3-8/lib/python3.8/site-packages/traitlets/traitlets.py:656: KeyError
```

**Comment by tswast** [comment]
Possibly an issue in tqdm: https://github.com/tqdm/tqdm/issues/1453

**Comment by tswast** [comment]
Second guess: https://github.com/jupyter-widgets/ipywidgets/pull/3533 -- looks like a dependency on ipykernel was removed even though we still need it?
