### ISSUE TITLE
Issue: google.api_core.exceptions.RetryError 

### ISSUE THREAD

**Issue by wad-youngjeonlee** [googleapis/python-bigquery#1570]
#### Problems
Hi There.
 
While developing and operating an application that reads Kafka Topic messages and stores them in a BigQuery table based on a docker container virtual environment on MacOS, a `Google.api_core.exceptions.RetryError` occurred in some containers.

I don't know what caused the `Google.api_core.exceptions.RetryError`. How should I solve it?

I am using [Use the legacy streaming API](https://cloud.google.com/bigquery/docs/streaming-data-into-bigquery#streaminginsertexamples)

#### Environment details

  - OS type and version: MacOS, MacBook Pro Apple M1 Max 2021
  - Python version: `[python --version](python:3.9-slim-buster)`
  - pip version: `pip --version`
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`
  - Google Cloud API: [Use the legacy streaming API](https://cloud.google.com/bigquery/docs/streaming-data-into-bigquery#streaminginsertexamples)

##### Dockerfile
```bash
# Dockerfile
# Use an official Python 3 runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# install app dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
```

##### requirements.txt
```
google-auth==2.3.3
google-auth-oauthlib==0.4.6
google-auth-httplib2==0.1.0
google-cloud-bigquery==3.10.0
kafka-python==2.0.2
```

#### Steps to reproduce

> Run the code below

#### Code example

```python
# example
consumer = KafkaConsumer(
        topic_name, 
        group_id=group_id, 
        bootstrap_servers=bootstrap_servers, 
        auto_offset_reset=auto_offset_reset, 
        value_deserializer=lambda m: json.loads(m.decode('utf-8'))
        )

    # credential
    key_path = '/app/key.json'  
    credentials = service_account.Credentials.from_service_account_file(key_path)
    client = bigquery.Client(credentials=credentials, project=credentials.project_id)

    # dataset_id = dataset_id
    # table_id = table_id # 

    # For loop
    while True:
        for message in consumer:
            try:
                data = message.value['data']
                metadata = message.value['metadata']

                data_dict = data
                metadata_dict = metadata

                key_value_data = {}
                key_value_data.update(data_dict)
                key_value_data.update({'cdc_timestamp':metadata_dict['timestamp']})
                key_value_data.update({'cdc_operation':metadata_dict['operation']})

                rows_to_insert = [key_value_data]

                # Insert rows into BigQuery table
                errors = client.insert_rows_json(table_id, rows_to_insert)  # Make an API request.

```

#### Stack trace
```
# example
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by wad-youngjeonlee** [comment]
@chalmerlowe  Really appreciate it!
I'll provide you more stacktrace


```
2023-05-24 21:33:48     response = self._make_request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
2023-05-24 21:33:48     response = conn.getresponse()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
2023-05-24 21:33:48     httplib_response = super().getresponse()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
2023-05-24 21:33:48     response.begin()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
2023-05-24 21:33:48     version, status, reason = self._read_status()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
2023-05-24 21:33:48     raise RemoteDisconnected("Remote end closed connection without"
2023-05-24 21:33:48 http.client.RemoteDisconnected: Remote end closed connection without response
2023-05-24 21:33:48 
2023-05-24 21:33:48 During handling of the above exception, another exception occurred:
2023-05-24 21:33:48 
2023-05-24 21:33:48 Traceback (most recent call last):
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
2023-05-24 21:33:48     resp = conn.urlopen(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-05-24 21:33:48     retries = retries.increment(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
2023-05-24 21:33:48     raise reraise(type(error), error, _stacktrace)
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
2023-05-24 21:33:48     raise value.with_traceback(tb)
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
2023-05-24 21:33:48     response = self._make_request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
2023-05-24 21:33:48     response = conn.getresponse()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
2023-05-24 21:33:48     httplib_response = super().getresponse()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
2023-05-24 21:33:48     response.begin()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
2023-05-24 21:33:48     version, status, reason = self._read_status()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
2023-05-24 21:33:48     raise RemoteDisconnected("Remote end closed connection without"
2023-05-24 21:33:48 urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-05-24 21:33:48 
2023-05-24 21:33:48 During handling of the above exception, another exception occurred:
2023-05-24 21:33:48 
2023-05-24 21:33:48 Traceback (most recent call last):
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
2023-05-24 21:33:48     return target()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 482, in api_request
2023-05-24 21:33:48     response = self._make_request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 341, in _make_request
2023-05-24 21:33:48     return self._do_request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 379, in _do_request
2023-05-24 21:33:48     return self.http.request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/auth/transport/requests.py", line 480, in request
2023-05-24 21:33:48     response = super(AuthorizedSession, self).request(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
2023-05-24 21:33:48     resp = self.send(prep, **send_kwargs)
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
2023-05-24 21:33:48     r = adapter.send(request, **kwargs)
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
2023-05-24 21:33:48     raise ConnectionError(err, request=request)
2023-05-24 21:33:48 requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-05-24 21:33:48 
2023-05-24 21:33:48 The above exception was the direct cause of the following exception:
2023-05-24 21:33:48 
2023-05-24 21:33:48 Traceback (most recent call last):
2023-05-24 21:33:48   File "/app/main.py", line 23, in <module>
2023-05-24 21:33:48     main(args)
2023-05-24 21:33:48   File "/app/main.py", line 12, in main
2023-05-24 21:33:48     utils.consume_kafka_and_insert_bigquery(args.topic_name, args.group_id, args.auto_offset_reset, args.table_id)
2023-05-24 21:33:48   File "/app/utils.py", line 164, in consume_kafka_and_insert_bigquery
2023-05-24 21:33:48     errors = client.insert_rows_json(table_id, rows_to_insert)  # Make an API request.
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 3688, in insert_rows_json
2023-05-24 21:33:48     response = self._call_api(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 813, in _call_api
2023-05-24 21:33:48     return call()
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
2023-05-24 21:33:48     return retry_target(
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 205, in retry_target
2023-05-24 21:33:48     raise exceptions.RetryError(
2023-05-24 21:33:48 google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function, last exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by dbalogVEP** [comment]
@wad-youngjeonlee I ran into the same exception while calling `insert_rows_json()`.  It turned out I was sending more than 10MB in a single request.  Big Query has a limit of [10MB per http request and 10MB per row.](https://cloud.google.com/bigquery/quotas#streaming_inserts) 
After I added some code to track how big the request would be and kept it under 10MB, this exception went away.

**Comment by chalmerlowe** [comment]
@wad-youngjeonlee In looking at the stacktrace, the original cause of the error appears to be that we are not getting an appropriate response quick enough as shown in the first few lines of the stacktrace, where the `http` library begins to complain.

```
2023-05-24 21:33:48   File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
2023-05-24 21:33:48     raise RemoteDisconnected("Remote end closed connection without"
2023-05-24 21:33:48 http.client.RemoteDisconnected: Remote end closed connection without response
```

As noted by @dbalogVEP there are a number of potential problems that might cause the http request to fail such as exceeding the limits of the BigQuery system.

As a starting point, I would evaluate what might be causing the system to drop the http connection, i.e. by potentially by sending very small queries as tests.

**Comment by chalmerlowe** [comment]
Closing this as will not work. If you still need help, please feel free to reopen this Issue.
