### ISSUE TITLE
Importing google-cloud-bigquery broken on Python 3.12

### ISSUE THREAD

**Issue by bendelany** [googleapis/python-bigquery#1710]
We are seeing the error below during an import of version 3.13.0 of google-cloud-bigquery while running Python 3.12.

```
 Traceback (most recent call last):
   File "F:\Tools\Agent-1\_work\r2856\a\_fhir_scheduled_query_table\scheduledQueryTable\create__table.py", line 4, in <module>
    from google.cloud.bigquery.client import Client
   File "F:\Tools\python\Lib\site-packages\google\cloud\bigquery\__init__.py", line 35, in <module>
     from google.cloud.bigquery.client import Client
  File "F:\Tools\python\Lib\site-packages\google\cloud\bigquery\client.py", line 60, in <module>
     import google.api_core.exceptions as core_exceptions
   File "F:\Tools\python\Lib\site-packages\google\api_core\exceptions.py", line 29, in <module>
     from google.rpc import error_details_pb2
   File "F:\Tools\python\Lib\site-packages\google\rpc\__init__.py", line 18, in <module>
    import pkg_resources
   File "F:\Tools\python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
     register_finder(pkgutil.ImpImporter, find_on_path)
                     ^^^^^^^^^^^^^^^^^^^
 AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

It seems the error is due to imports pulled in while importing the BigQuery client.

Is there a fix for this without reverting to Python 3.11?

**Comment by Linchin** [comment]
Hi @bendelany, thank you for bringing this up. Right now we do not support Python 3.12. This will be done in coordination with the rest of the google cloud clients, but we don't have a timeline yet.
