### ISSUE TITLE
Can't create QueryJobConfig with an empty array of structs as a query parameter

### ISSUE THREAD

**Issue by Oscar-Cunningham** [googleapis/python-bigquery#2073]
#### Environment details

  - Tested on MacOS 15.1, also tested on Alpine Linux
  - Python version: 3.13.0 (also tested on 3.12)
  - pip version: 24.3.1
  - `google-cloud-bigquery` version: 3.27.0 (also tested on 3.5.0)

#### Steps to reproduce

  1. Run code example

#### Code example

```python
from google.cloud import bigquery
bigquery.QueryJobConfig(
    query_parameters=[
        bigquery.ArrayQueryParameter(
            'data',
            bigquery.StructQueryParameterType(
                bigquery.SchemaField('example_field', 'STRING').to_standard_sql()
            ),
            []
        )
    ]
)
```

#### Stack trace
```
Traceback (most recent call last):
  File "<python-input-0>", line 2, in <module>
    bigquery.QueryJobConfig(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        query_parameters=[
        ^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        ]
        ^
    )
    ^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/query.py", line 336, in __init__
    super(QueryJobConfig, self).__init__("query", **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/base.py", line 183, in __init__
    setattr(self, prop, val)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/base.py", line 191, in __setattr__
    super(_JobConfig, self).__setattr__(name, value)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/query.py", line 584, in query_parameters
    self._set_sub_prop("queryParameters", _to_api_repr_query_parameters(values))
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/query.py", line 110, in _to_api_repr_query_parameters
    return [query_parameter.to_api_repr() for query_parameter in value]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/query.py", line 742, in to_api_repr
    a_type = self.array_type.to_api_repr()
  File "/Users/example.user/example_python_project/.venv/lib/python3.13/site-packages/google/cloud/bigquery/query.py", line 345, in to_api_repr
    if field.description is not None:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'StandardSqlField' object has no attribute 'description'
```

**Comment by Oscar-Cunningham** [comment]
Ah, never mind. The above code is confused
