### ISSUE TITLE
module 'google.cloud.bigquery_storage_v1.types' has no attribute 'DataFormat'

### ISSUE THREAD

**Issue by RobbieShan** [googleapis/python-bigquery#317]
- I'm running Python 3.8.5 locally.
- I have upgraded to the latest googleapis
- I am connecting my local code to my bq table in my project
- I am able to run the query successfully and iterate through it
- However, when I try to export the dataset to a pandas dataframe I get the AttributeError above

```
   query_job = bqclient.query(QUERY)  # API request
    rows = query_job.result()  # Waits for query to finish
    print(rows.total_rows)

    for row in rows:  print(row)   #<--- This runs just fine

    df = rows.to_dataframe(bqstorage_client=bqstorageclient)  
    #This errors out with module 'google.cloud.bigquery_storage_v1.types' has no attribute 'DataFormat'

```
Here is the complete trace:

```
Traceback (most recent call last):
  File "C:\Users\ravi_\anaconda3\envs\pythonProject\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0ad504af515e>", line 1, in <module>
    runfile('C:/Users/ravi_/PycharmProjects/pythonProject/main.py', wdir='C:/Users/ravi_/PycharmProjects/pythonProject')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ravi_/PycharmProjects/pythonProject/main.py", line 42, in <module>
    print_hi('PyCharm')
  File "C:/Users/ravi_/PycharmProjects/pythonProject/main.py", line 35, in print_hi
    df = rows.to_dataframe(bqstorage_client=bqstorageclient)
  File "C:\Users\ravi_\anaconda3\envs\pythonProject\lib\site-packages\google\cloud\bigquery\table.py", line 1687, in to_dataframe
    record_batch = self.to_arrow(
  File "C:\Users\ravi_\anaconda3\envs\pythonProject\lib\site-packages\google\cloud\bigquery\table.py", line 1507, in to_arrow
    for record_batch in self._to_arrow_iterable(
  File "C:\Users\ravi_\anaconda3\envs\pythonProject\lib\site-packages\google\cloud\bigquery\table.py", line 1397, in _to_page_iterable
    for item in bqstorage_download():
  File "C:\Users\ravi_\anaconda3\envs\pythonProject\lib\site-packages\google\cloud\bigquery\_pandas_helpers.py", line 615, in _download_table_bqstorage
    table=table.to_bqstorage(), data_format=bigquery_storage.types.DataFormat.ARROW
AttributeError: module 'google.cloud.bigquery_storage_v1.types' has no attribute 'DataFormat' 
```

Any guidance would be appreciated.

**Comment by tswast** [comment]
Can you share the output of `pip freeze` or `conda list`?

The types moved in `google-cloud-bigquery-storage` version 2.0, and `google-cloud-bigquery` version 2.0 was updated to use these moved types.

**Comment by RobbieShan** [comment]
Here you go

```
conda list
# packages in environment at C:\Users\ravi_\anaconda3\envs\pythonProject:
#
# Name                    Version                   Build  Channel
abseil-cpp                20200225.2           ha925a31_2    conda-forge
aiohttp                   3.6.2            py38he774522_0  
arrow-cpp                 1.0.1           py38h7c1416e_13_cpu    conda-forge
async-timeout             3.0.1                    py38_0  
attrs                     20.2.0                     py_0  
aws-c-common              0.4.59               ha925a31_0  
aws-c-event-stream        0.1.6                h9490e6b_5    conda-forge
aws-checksums             0.1.9                h25771f4_2    conda-forge
aws-sdk-cpp               1.8.59               h5029227_1    conda-forge
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
brotli                    1.0.9                h33f27b4_0  
brotlipy                  0.7.0           py38he774522_1000  
bzip2                     1.0.8                he774522_0  
c-ares                    1.16.1               he774522_0  
ca-certificates           2020.7.22                     0  
cachetools                4.1.1                      py_0  
certifi                   2020.6.20                py38_0  
cffi                      1.14.3           py38h7a1dbc1_0  
chardet                   3.0.4                 py38_1003  
colorama                  0.4.3                      py_0  
cryptography              3.1.1            py38h7a1dbc1_0  
cycler                    0.10.0                   py38_0  
decorator                 4.4.2                      py_0  
fastavro                  1.0.0.post1      py38he774522_0  
freetype                  2.10.2               hd328e21_0  
gflags                    2.2.2                ha925a31_0  
glog                      0.4.0                h33f27b4_0  
google-api-core           1.22.2           py38h21ff451_0  
google-api-core-grpc      1.22.2               h21ff451_0  
google-auth               1.22.1                     py_0  
google-cloud-bigquery     2.1.0              pyhc8dfbb8_0    conda-forge
google-cloud-bigquery-core 2.1.0              pyhc8dfbb8_0    conda-forge
google-cloud-bigquery-datatransfer 1.0.0              pyh9f0ad1d_0    conda-forge
google-cloud-bigquery-storage 1.1.0              pyh9f0ad1d_0    conda-forge
google-cloud-bigquery-storage-core 1.1.0            py38hc8b782b_0    conda-forge
google-cloud-core         1.4.3                      py_0  
google-cloud-storage      1.31.0                     py_0  
google-crc32c             1.0.0            py38he774522_0  
google-resumable-media    1.1.0                      py_1  
googleapis-common-protos  1.52.0           py38h21ff451_0  
grpc-cpp                  1.32.0               h5fb862e_1    conda-forge
grpcio                    1.31.0           py38he7da953_0  
icu                       58.2                 ha925a31_3  
idna                      2.10                       py_0  
intel-openmp              2020.2                      254  
ipython                   7.18.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
jedi                      0.17.2                   py38_0  
jpeg                      9b                   hb83a4c4_2  
kiwisolver                1.2.0            py38h74a9793_0  
krb5                      1.18.2               hc04afaa_0  
libcrc32c                 1.1.1                ha925a31_2  
libcurl                   7.71.1               h2a8f88b_1  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.13.0.1             h200bbdf_0    conda-forge
libssh2                   1.9.0                h7a1dbc1_1  
libthrift                 0.13.0               hdfef310_6    conda-forge
libtiff                   4.1.0                h56a325e_1  
libutf8proc               2.5.0                he774522_2  
lz4-c                     1.9.2                hf4a77e7_3  
matplotlib                3.3.1                         0  
matplotlib-base           3.3.1            py38hba9282a_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38hb782905_0  
mkl_fft                   1.2.0            py38h45dec08_0  
mkl_random                1.1.1            py38h47e9c7a_0  
multidict                 4.7.6            py38he774522_1  
numpy                     1.19.1           py38h5510c5b_0  
numpy-base                1.19.1           py38ha3acd2a_0  
olefile                   0.46                       py_0  
openssl                   1.1.1h               he774522_0  
pandas                    1.1.3            py38ha925a31_0  
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pickleshare               0.7.5                 py38_1000  
pillow                    7.2.0            py38hcc1f983_0  
pip                       20.2.3                   py38_0  
prompt-toolkit            3.0.7                      py_0  
proto-plus                1.10.0             pyh9f0ad1d_0    conda-forge
protobuf                  3.13.0           py38h33f27b4_1  
pyarrow                   1.0.1           py38hc564555_13_cpu    conda-forge
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.20                       py_2  
pygments                  2.7.1                      py_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38ha925a31_4  
pysocks                   1.7.1                    py38_0  
python                    3.8.5                h5fd99cc_1  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
qt                        5.9.7            vc14h73c81de_0  
re2                       2020.10.01           ha925a31_0    conda-forge
requests                  2.24.0                     py_0  
rsa                       4.6                        py_0  
setuptools                50.3.0           py38h9490d1a_1  
simpy                     4.0.1                    pypi_0    pypi
sip                       4.19.13          py38ha925a31_0  
six                       1.15.0                     py_0  
snappy                    1.1.8                h33f27b4_0  
sqlite                    3.33.0               h2a8f88b_0  
tk                        8.6.10               he774522_0  
tornado                   6.0.4            py38he774522_1  
tqdm                      4.50.2                     py_0  
traitlets                 5.0.4                      py_0  
urllib3                   1.25.10                    py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_3  
wcwidth                   0.2.5                      py_0  
wheel                     0.35.1                     py_0  
win_inet_pton             1.1.0                    py38_0  
wincertstore              0.2                      py38_0  
xlrd                      1.2.0                      py_0  
xz                        5.2.5                h62dcd97_0  
yarl                      1.6.0            py38he774522_0  
zlib                      1.2.11               h62dcd97_4  
zstd                      1.4.5                h04227a9_0  
Note: you may need to restart the kernel to use updated packages.
```

**Comment by tseaver** [comment]
@RobbieShan you need to update `google-cloud-bigquery-storage` to a version >= `2.0.0`.  (I don't know what the `-core` one could be.  @tswast is that some conda-specific breakout?).

**Comment by tswast** [comment]
`google-cloud-bigquery-storage-core` is the package without any "extras". In conda we default to installing everything.

Strange that it ended up in this state. Sounds like I need to look at the requirements in the conda recipe.

**Comment by RobbieShan** [comment]
Thank you folks - that fixed it. Per @tseaver I had to update `google-cloud-bigquery-storage` to 2.0.0. Conda upgrade doesn't detect this.
