### ISSUE TITLE
ImportError: pandas-gbq requires google-cloud-bigquery: cannot import name 'Compression' from 'google.cloud.bigquery.enums'

### ISSUE THREAD

**Issue by K11K11** [googleapis/python-bigquery#427]
**Error:**
This error occurs when I try to use df.to_gbq in order to write to an existing table in Google Big Query: _ImportError: pandas-gbq requires google-cloud-bigquery: cannot import name 'Compression' from 'google.cloud.bigquery.enums'_

**Versions used:**
`pandas version: 1.1.3`
`pandas-gbq: 0.14.1`
`conda version: 4.8.5`
`google-cloud-bigquery version: 2.6.0`

**Code example:**
`df.to_gbq(destination_table = 'table_name', project_id = 'project', if_exists='append')`

**Stack trace:**
Traceback (most recent call last):
  File "/_directory_/lib/python3.8/site-packages/pandas_gbq/gbq.py", line 106, in _test_google_api_imports
    from google.cloud import bigquery  # noqa
  File "/_directory_/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/_directory_/anaconda3/envs/revapp/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 63, in <module>
    from google.cloud.bigquery import job
  File "/_directory_/lib/python3.8/site-packages/google/cloud/bigquery/job/__init__.py", line 37, in <module>
    from google.cloud.bigquery.enums import Compression
ImportError: cannot import name 'Compression' from 'google.cloud.bigquery.enums' (/_directory_/lib/python3.8/site-packages/google/cloud/bigquery/enums.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_directory_/_file_.py", line 649, in <module>
    df.to_gbq(destination_table = '_table-name_, project_id = '_project_', if_exists='append')
  File "/_directory_/lib/python3.8/site-packages/pandas/core/frame.py", line 1646, in to_gbq
    gbq.to_gbq(
  File "/_directory_/lib/python3.8/site-packages/pandas/io/gbq.py", line 215, in to_gbq
    pandas_gbq.to_gbq(
  File "/_directory_/lib/python3.8/site-packages/pandas_gbq/gbq.py", line 1120, in to_gbq
    _test_google_api_imports()
  File "/_directory_/lib/python3.8/site-packages/pandas_gbq/gbq.py", line 108, in _test_google_api_imports
    raise ImportError(
ImportError: pandas-gbq requires google-cloud-bigquery: cannot import name 'Compression' from 'google.cloud.bigquery.enums' (/_directory_/lib/python3.8/site-packages/google/cloud/bigquery/enums.py)

**Comment by HemangChothani** [comment]
@K11K11 Not able to reproduce it, please provide more details or try with the fresh environment.

Tested environment details and sample code are following:

```python
import pandas
import pandas_gbq

df = pandas.DataFrame(
    {
        "my_string": ["a", "b", "c"],
        "my_int64": [1, 2, 3],
        "my_float64": [4.0, 5.0, 6.0],
        "my_bool1": [True, False, True],
        "my_bool2": [False, True, False],
        "my_dates": pandas.date_range("now", periods=3),
    }
pandas_gbq.to_gbq(df, table_id, project_id=project_id)
```

environment details:

    google-cloud-bigquery==2.6.0
    google-cloud-bigquery-storage==2.1.0
    pandas==1.1.3
    pandas-gbq==0.14.1

**Comment by K11K11** [comment]
I updated `google-cloud-bigquery-storage` to `2.1.0` (rest are the same) but the problem is still there. Not sure what other details would you require me to provide?

**Comment by HemangChothani** [comment]
@K11K11 Could you please try with the fresh (new) environment? I am still unable to reproduce it.

**Comment by K11K11** [comment]
Uninstalled and reinstalled the packages and it now works fine.
