### ISSUE TITLE
When specifying a default dataset, you shouldn't have to specify a project if it's going to be determined from credentials

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery#842]
```
>>> client = bigquery.Client(
    default_query_job_config=bigquery.job.QueryJobConfig(
        default_dataset='riversnake'))
... ... Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/job/query.py", line 231, in __init__
    super(QueryJobConfig, self).__init__("query", **kwargs)
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/job/base.py", line 708, in __init__
    setattr(self, prop, val)
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/job/base.py", line 716, in __setattr__
    super(_JobConfig, self).__setattr__(name, value)
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/job/query.py", line 312, in default_dataset
    value = DatasetReference.from_string(value)
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/dataset.py", line 339, in from_string
    raise ValueError(
ValueError: When default_project is not set, dataset_id must be a fully-qualified dataset ID in standard SQL format, e.g., "project.dataset_id" got riversnake
>>> client = bigquery.Client()
>>> client.project
'<default project>'
```

**Comment by tswast** [comment]
I'd consider this a feature request.

To implement it, we'd have to check whenever we use a reference if the project isn't set, since it is required in the API representation. We already have a `default_project` argument on `from_string`.

I could see an optional argument to `to_api_repr` that raises if `self._project` isn't set and `default_project` is `None` being useful for this implementation.

**Comment by tswast** [comment]
Likely we'll need to update anywhere we use `TableReference` with similar logic, otherwise folks will have similar complaints.

**Comment by tswast** [comment]
Might even have to be a breaking change if we no longer throw on `from_string` when a project isn't set.

**Comment by tswast** [comment]
Or... we could try to fix this just for the "defaults" use case. I like that idea better...

**Comment by chalmerlowe** [comment]
Closing as will not fix.
