### ISSUE TITLE
Application Default Credentials failing over to load_credentials_from_file 

### ISSUE THREAD

**Issue by James-DBA-Anderson** [googleapis/python-bigquery#878]
- `google-cloud-bigquery` version: `2.20.0`

I'm trying to build a data pipeline that uses [target-bigquery](https://github.com/adswerve/target-bigquery/issues/19) on Google Composer (AirFlow on GKE) that is running under a service account that has access to BigQuery. 

My understanding is that Google client libraries will attempt to use the service account attached to resource that is running the code, in this case, that is a pod in GKE that is using the default node pool to use the cluster's service account. This is [Application Default Credentials](https://cloud.google.com/docs/authentication/production#best_practices_for_managing_credentials) (ADC).

target-bigquery [builds the BigQuery client](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/utils.py) like this:
```
from google.cloud.bigquery import DatasetReference
client = bigquery.Client(project=project_id, location=location)
```

So I should be able to run target-bigquery on GKE without a client_credentials.json file but I get the the following error:

#### Stack trace
```
target-bigquery | Traceback (most recent call last):
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/bin/target-bigquery", line 8, in <module>
target-bigquery |     sys.exit(main())
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/__init__.py", line 61, in main
target-bigquery |     client, dataset = ensure_dataset(project_id, dataset_id, location)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/utils.py", line 28, in ensure_dataset
target-bigquery |     client = bigquery.Client(project=project_id, location=location)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 179, in __init__
target-bigquery |     project=project, credentials=credentials, _http=_http
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 320, in __init__
target-bigquery |     self, credentials=credentials, client_options=client_options, _http=_http
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 178, in __init__
target-bigquery |     credentials, _ = google.auth.default(scopes=scopes)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 459, in default
target-bigquery |     credentials, project_id = checker()
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
target-bigquery |     os.environ[environment_vars.CREDENTIALS]
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
target-bigquery |     "File {} was not found.".format(filename)
target-bigquery | google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
meltano         | Loading failed (1): google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
meltano         | ELT could not be completed: Loader failed
ELT could not be completed: Loader failed
```

This is strange, because looking into the error trace I can see that load_credentials_from_file in _get_explicit_environ_credentials in the _default module is being called. This only get's called if the env var GOOGLE_APPLICATION_CREDENTIALS is not none.

I have not set the environment variable GOOGLE_APPLICATION_CREDENTIALS.

Running env or printenv doesn't show it but the code seems to be seeing it and it has the value /projects/client_secrets.json. I tried setting GOOGLE_APPLICATION_CREDENTIALS to '' which it does see and obviously fails.

Is there anything that could cause a call to load_credentials_from_file other than the existence of the GOOGLE_APPLICATION_CREDENTIALS env var?

Thanks

**Comment by tswast** [comment]
@leahecole Can you chime in on how credentials are loaded in Cloud Composer?

**Comment by leahecole** [comment]
Hey! Happy to comment. So I haven't seen this before and have a few questions before I speculate about what's happening auth-wise. Just in case you haven't seen it though, here's [the doc for Service accounts + Composer](https://cloud.google.com/composer/docs/how-to/access-control#about-service). 

1. What kind of Operator are you using to run this code? (PythonOperator? KubernetesPodOperator? GKEStartPodOperator?) 
2. Can you share a little more info about the operator code you're using?


One thing I would suggest is poking around the pods in GKE and seeing if there's an env_var set somewhere. For any pod in GKE, you can go to the YAML tab and if env_vars are set you will see them. This screenshot is from a pod launched with the KubernetesPodOperator where I explicitly set an environment variable.
![8WGGn6ySoJJA8ww](https://user-images.githubusercontent.com/6719667/129810835-7654bbb0-0a00-4bb1-87af-5ae7544ebfbd.png)

If you're using the GKEStartPodOperator, look at the workloads in your cluster and check out the pod. If you're using the KubernetesPodOperator, use the "View workloads" button from the Cloud Console "Environment Configuration" page for your Composer environment, look for your pod, and check out the YAML tab. If you're using the PythonOperator, I think you would look at the airflow-worker pods, but I'm not 100% certain on that. I rarely ever use the PythonOperator because I always use Operators that send the heavy lifting to other services.

**Comment by James-DBA-Anderson** [comment]
Hi @leahecole 

I'm just starting on this again today after being pulled onto something else. Thanks for your response. 

I am using the KubernetesPodOperator. I checked the YAML tab in workloads and there was no mention of the GOOGLE_APPLICATION_CREDENTIALS env var. I could only see the one env vars that I am passing into the KubernetesPodOperator.

I can happily use the the BigQuery airflow operators on the same cluster without exporting a key, so I'm really confused why my container that is initiated via the KubernetesPodOperator is not picking up the same credentials.

I've attached the error stack below to show the flow that the bigquery client takes before logging the "File /project/client_secrets.json was not found" error.

I'm sure I'm missing something simple, but I'm really finding it hard to see it. Any help would be appreciated.

```
[2021-10-01 11:16:52,874] {pod_launcher.py:149} INFO - target-bigquery | Traceback (most recent call last):
[2021-10-01 11:16:52,875] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/bin/target-bigquery", line 8, in <module>
[2021-10-01 11:16:52,875] {pod_launcher.py:149} INFO - target-bigquery |     sys.exit(main())
[2021-10-01 11:16:52,875] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/__init__.py", line 68, in main
[2021-10-01 11:16:52,876] {pod_launcher.py:149} INFO - target-bigquery |     client, dataset = ensure_dataset(project_id, dataset_id, location)
[2021-10-01 11:16:52,876] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/utils.py", line 43, in ensure_dataset
[2021-10-01 11:16:52,877] {pod_launcher.py:149} INFO - target-bigquery |     client = bigquery.Client(project=project_id, location=location)
[2021-10-01 11:16:52,877] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 210, in __init__
[2021-10-01 11:16:52,878] {pod_launcher.py:149} INFO - target-bigquery |     _http=_http,
[2021-10-01 11:16:52,878] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 318, in __init__
[2021-10-01 11:16:52,878] {pod_launcher.py:149} INFO - target-bigquery |     self, credentials=credentials, client_options=client_options, _http=_http
[2021-10-01 11:16:52,879] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 176, in __init__
[2021-10-01 11:16:52,879] {pod_launcher.py:149} INFO - target-bigquery |     credentials, _ = google.auth.default(scopes=scopes)
[2021-10-01 11:16:52,879] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 457, in default
[2021-10-01 11:16:52,879] {pod_launcher.py:149} INFO - target-bigquery |     credentials, project_id = checker()
[2021-10-01 11:16:52,880] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 220, in _get_explicit_environ_credentials
[2021-10-01 11:16:52,880] {pod_launcher.py:149} INFO - target-bigquery |     os.environ[environment_vars.CREDENTIALS]
[2021-10-01 11:16:52,880] {pod_launcher.py:149} INFO - target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 106, in load_credentials_from_file
[2021-10-01 11:16:52,881] {pod_launcher.py:149} INFO - target-bigquery |     "File {} was not found.".format(filename)
[2021-10-01 11:16:52,881] {pod_launcher.py:149} INFO - target-bigquery | google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
[2021-10-01 11:16:52,981] {pod_launcher.py:149} INFO - meltano         | Loading failed (1): google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
```

**Comment by James-DBA-Anderson** [comment]
Hi this can be closed. I figured out that there was some default config for my target-bigquery data loader that was causing the GOOGLE_APPLICATION_CREDENTIALS env var to be created. Once I overrode this config everything worked. Thanks
