### ISSUE TITLE
Protobuf TypeError on import after upgrade

### ISSUE THREAD

**Issue by wrossmorrow** [googleapis/python-bigquery#881]
I upgraded and can no longer `import` `bigquery`: 
```
TypeError: descriptor to field 'google.protobuf.FileDescriptorProto.name' doesn't apply to 'FileDescriptorProto' object
```

#### Environment details

  - MacOSX 10.15.7
  - `Python 3.9.2`
  - `pip 21.2.2`
  - `Name: google-cloud-bigquery Version: 2.24.0`

#### Steps to reproduce

  1. `pip install --upgrade google-cloud-bigquery`
  2. `from google.cloud import bigquery`

#### Code example

```python
>>> from google.cloud import bigquery
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 70, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 45, in <module>
    from google.cloud.bigquery import schema
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/schema.py", line 20, in <module>
    from google.cloud.bigquery_v2 import types
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery_v2/__init__.py", line 18, in <module>
    from .types.encryption_config import EncryptionConfiguration
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery_v2/types/__init__.py", line 16, in <module>
    from .encryption_config import EncryptionConfiguration
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery_v2/types/encryption_config.py", line 26, in <module>
    class EncryptionConfiguration(proto.Message):
  File "/usr/local/lib/python3.9/site-packages/proto/message.py", line 200, in __new__
    file_info = _file_info._FileInfo.maybe_add_descriptor(filename, package)
  File "/usr/local/lib/python3.9/site-packages/proto/_file_info.py", line 42, in maybe_add_descriptor
    descriptor=descriptor_pb2.FileDescriptorProto(
TypeError: descriptor to field 'google.protobuf.FileDescriptorProto.name' doesn't apply to 'FileDescriptorProto' object
```

**Comment by wrossmorrow** [comment]
Appears to also require a `protobuf` upgrade: 
```
$ pip install --upgrade protobuf
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://pypi.org/simple
Requirement already satisfied: protobuf in /usr/local/lib/python3.9/site-packages (3.15.8)
Collecting protobuf
  Using cached protobuf-3.17.3-cp39-cp39-macosx_10_9_x86_64.whl (1.0 MB)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.9/site-packages (from protobuf) (1.16.0)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.15.8
    Uninstalling protobuf-3.15.8:
      Successfully uninstalled protobuf-3.15.8
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed protobuf-3.17.3
WARNING: You are using pip version 21.2.2; however, version 21.2.4 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
$ python
Python 3.9.2 (default, Mar 26 2021, 23:27:12) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigquery
>>> 
```

**Comment by tswast** [comment]
Odd. We test with protobuf 3.12.0 on Python 3.6 and haven't encountered this: https://github.com/googleapis/python-bigquery/blob/2cb3563ee863edef7eaf5d04d739bcfe7bc6438e/testing/constraints-3.6.txt#L18

**Comment by meredithslota** [comment]
@wrossmorrow We cannot reproduce this issue — are you still encountering it?
