### ISSUE TITLE
Fetching interval data as arrow using the storage API results in an internal error.

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery#949]
Given:

```
create table i (v interval)

insert into i (v) values (make_interval(1, 2, 3, 4, 5, 6))
```

Trying to fetch data as arrow:

```
client.query("select * from i").to_arrow()
Traceback (most recent call last):
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 156, in error_remapped_callable
    return _StreamingResponseIterator(
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 82, in __init__
    self._stored_first_result = next(self._wrapped)
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "there was an error operating on 'projects/precise-truck-742/locations/us/sessions/CAISDHhNamxVZlFxeVl6ahoCamQaAmly/streams/GgJqZBoCaXIoAg': internal error"
	debug_error_string = "{"created":"@1631023112.273838647","description":"Error received from peer ipv6:[2607:f8b0:400f:803::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"there was an error operating on 'projects/precise-truck-742/locations/us/sessions/CAISDHhNamxVZlFxeVl6ahoCamQaAmly/streams/GgJqZBoCaXIoAg': internal error","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/job/query.py", line 1474, in to_arrow
    return query_result.to_arrow(
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/table.py", line 1794, in to_arrow
    for record_batch in self._to_arrow_iterable(
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/table.py", line 1692, in _to_page_iterable
    yield from result_pages
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/_pandas_helpers.py", line 786, in _download_table_bqstorage
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jim/p/g/python-bigquery/google/cloud/bigquery/_pandas_helpers.py", line 655, in _download_table_bqstorage_stream
    reader = bqstorage_client.read_rows(stream.name)
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/client.py", line 124, in read_rows
    stream = gapic_client.read_rows(
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/bigquery_storage_v1/services/big_query_read/client.py", line 598, in read_rows
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 142, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/timeout.py", line 99, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/jim/p/g/python-bigquery/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 160, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 there was an error operating on 'projects/precise-truck-742/locations/us/sessions/CAISDHhNamxVZlFxeVl6ahoCamQaAmly/streams/GgJqZBoCaXIoAg': internal error
```

**Comment by jimfulton** [comment]
https://issuetracker.google.com/issues/199112223
